### ISSUE TITLE
Uncaught ReferenceError: reject is not defined

### ISSUE THREAD

**Issue by edarblanco** [atom/ide-typescript#149]
[Enter steps to reproduce:]

1. Activate or Deactivate
2. ...

**Atom**: 1.34.0 x64
**Electron**: 3.1.4
**OS**: "Arch Linux"
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.8.0

### Stack Trace

Uncaught ReferenceError: reject is not defined

```
At /home/edar/.atom/packages/ide-typescript/lib/main.js:96

ReferenceError: reject is not defined
    at setTimeout (/packages/ide-typescript/lib/main.js:96:11)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-dark-fusion-syntax 2.2.1 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-import-cost 1.2.0 
atom-vue-router 0.3.0 
autoclose-html 0.23.0 
autocomplete-modules 2.3.0 
autoimport 0.3.0 
busy-signal 2.0.0 
color-picker 2.3.0 
css-snippets 1.1.0 
emmet-atom-plugin 0.0.1 
es6-javascript 1.0.0 
expressjs 2.2.0 
file-icons 2.1.30 
highlight-selected 0.14.0 
hyperclick 0.0.0 
ide-css 0.3.2 
ide-flowtype 0.24.0 
ide-html 0.5.0 
ide-json 0.2.1 
ide-standardjs 0.0.1 
ide-typescript 0.8.0 
ide-vue 0.1.9 
intentions 1.1.5 
javascript-snippets 1.2.1 
js-hyperclick 1.13.3 
language-babel 2.85.0 
language-graphql 1.0.0 
language-vue 0.24.0 
language-vuetify 0.3.0 
minimap 4.29.9 
minimap-autohider 1.6.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
modern-javascript-snippets 1.1.0 
pigments 0.40.2 
platformio-ide-terminal 2.9.1 
todo-show 2.3.2 
turbo-javascript 1.4.0 
vue-atom-snippets 1.2.0 
vue-format 0.4.0 
vue-hyperclick 0.2.0 
vuejs2-snippets 1.1.0 
vuetify-atom 0.2.2 
zentabs 0.8.9 
```

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by seanodell** [comment]
Was directed to this issue from within Atom. I definitely installed an official build of Atom. I don't want to create a new issue if Atom is directing people to this one.

```
1. Deactivate ide-typescript
2. Activate ide-typescript

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.8.0


### Stack Trace

Uncaught ReferenceError: reject is not defined

```
At /Users/seaodell/.atom/packages/ide-typescript/lib/main.js:96

ReferenceError: reject is not defined
    at setTimeout (/packages/ide-typescript/lib/main.js:96:11)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-runner 2.7.1 
atom-typescript 13.2.1 
build 0.70.0 
build-npm-apm 0.12.0 
build-tools-ant 0.1.4 
busy-signal 2.0.1 
chmod 0.1.1 
data-atom 0.29.1 
default-language 0.3.1 
document-outline 2.1.2 
ide-typescript 0.8.0 
insert-timestamp 0.2.4 
iso8601-timestamp 0.1.1 
language-applescript 0.3.0 
language-plantuml 0.2.0 
linter 2.3.0 
linter-tslint 1.10.22 
local-history 4.3.1 
markdown-preview-plus 3.8.1 
plantuml-viewer 0.7.2 
platformio-ide-terminal 2.9.1 
pretty-json 2.1.2 
script 3.18.1 
script-runner 2.3.1 
sort-lines 0.19.0 
svg-preview 0.14.0 
xml-formatter 0.13.0 
```

**Comment by 50Wliu** [comment]
@seanodell thanks for commenting - I've reopened this issue.

**Comment by UziTech** [comment]
Looks like this was fixed in https://github.com/atom/ide-typescript/commit/cbd9441b8550b0a12f8580372e8c8e2366c66349

We just need a new release.

**Comment by UziTech** [comment]
related issue https://github.com/atom/ide-typescript/issues/142

**Comment by seanodell** [comment]
That was closed back in December. This just happened with the 1.36.1 release from April 9.

**Comment by UziTech** [comment]
the [latest release](https://github.com/atom/ide-typescript/releases/tag/v0.8.0) of `ide-typescript` was in November 2018

**Comment by seanodell** [comment]
Oh, thanks ... I thought I had that fix already and was thinking it was something new introduced by this newer release of atom because I just updated it. Didn't realize I still have the ide-typescript version with the problem, because it didn't occur to me that a fix would be sitting unreleased for 5 months. Hmm. Sounds like the project needs an owner?

**Comment by 50Wliu** [comment]
I just released 0.9.0, which should fix things!

> Sounds like the project needs an owner?

Yes, any help would be appreciated :)
